// 思路  复制一下广告组的fetch   然后实现一下批量替换campaign_id 和 aad_id  
// 如果需要新建广告组，就使用前面的接口
// 已有系列绑定id 
const bodyParams = {
    "campaign_id": "1811610896945169",
    "ad_infos": [
        {
            "ad_info": {
                "batch_info": [],
                "base_info": {
                    "struct_version": 1,
                    "app_name": "",
                    "vbo_date_type": 0,
                    "frequency_schedule": 0,
                    "ad_tag": [],
                    "shop_authorized_bc": "7417414952279097345",
                    "automated_targeting": 0,
                    "action_categories_v2": [],
                    "flow_package_include": [],
                    "action_days_v2": [],
                    "contextual_extend_type": 0,
                    "roas_bid": 0,
                    "include_custom_actions": [],
                    "source": "",
                    "anti_discrimination": 0,
                    "is_hfss": 0,
                    "frequency_type": 1,
                    "video_actions": [],
                    "auto_open": 0,
                    "internet_service_providers": [],
                    "ad_ref_pixel_id": "",
                    "video_actions_v2": [],
                    "start_time": "2024-10-01 02:55:31",
                    "smart_gender": 0,
                    "smart_audience": 0,
                    "ad_reach_frequency_buy_type": 0,
                    "identity_bc_id": "0",
                    "statistic_type": 0,
                    "ad_tag_v2": [],
                    "inventory_flow": [
                        3000
                    ],
                    "external_action": 96,
                    "retargeting_tags": [],
                    "identity_tts_shop_id": "0",
                    "cpa_auto": 0,
                    "ad_app_profile_page_type": 0,
                    "rf_predict_reach": 0,
                    "action_scene": [
                        2
                    ],
                    "name": "znx-10_01国庆2 fetch复制 fetch 广告户-test-0930-lc-1-无ms token sign-1",
                    "creative_display_mode": 0,
                    "operators_id": [],
                    "first_frame": [],
                    "end_time": "2034-10-01 02:55:31",
                    "gender": 0,
                    "ad_download_status": 0,
                    "budget_mode": 3,
                    "domain": "",
                    "campaign_id": 1811610896945169,
                    "exclude_custom_actions": [],
                    "promotion_target_type": 0,
                    "frequency": 0,
                    "cover_frequency_type": 0,
                    "catalog_authorized_bc": "0",
                    "android_osv": "",
                    "districts": [],
                    "flow_precision": 0,
                    "fallback_type": 0,
                    "ab_test_id": 0,
                    "interest_keywords_i18n": [],
                    "ad_keywords": [],
                    "identity_authorized_shop_id": "0",
                    "ad_id": "",
                    "city": [],
                    "retargeting_tags_exclude": [],
                    "brand_safety": 1,
                    "shop_type": 1,
                    "promotion_flow_type": 1,
                    "action_track_url": [],
                    "action_scenes_v2": [],
                    "daily_retention_ratio": 0,
                    "rf_predict_impression": 0,
                    "package": "",
                    "country": [
                        6252001
                    ],
                    "device_models": [],
                    "compensation_activity": 0,
                    "search_delivery_type": 0,
                    "external_url": "",
                    "spending_power_v2": [],
                    "secondary_toggle": 0,
                    "vast_moat": false,
                    "targeting_expansion": {
                        "expansion_enabled": false,
                        "expansion_types": []
                    },
                    "track_url": [],
                    "optimize_goal": 100,
                    "open_url": "",
                    "target_device_version": 0,
                    "native_type": 1,
                    "shop_id": "7495924793208440941",  // TODO: 店铺id
                    "deep_cpabid": 0,
                    "flow_control_mode": 1,
                    "platform": [
                        0
                    ],
                    "particle_locations": [
                        6252001
                    ],
                    "inventory_type": [],
                    "download_url": "",
                    "rf_predict_percentage": 0,
                    "smart_bid_type": 7,
                    "app_retargeting_install": false,
                    "cpv_video_duration_type": 0,
                    "external_type": 304,
                    "conversion_window": 0,
                    "cpa_bid_type": 0,
                    "cpa_skip_first_phrase": 1,
                    "ios14_quota_type": 1,
                    "pricing": 9,
                    "bid_display_mode": 0,
                    "identity_id": "",
                    "ios_osv": "",
                    "promotion_website_type": 0,
                    "is_share_disable": 0,
                    "is_comment_disable": 0,
                    "exclude_app_package_id": 0,
                    "budget": 20,
                    "product_source": 2,
                    "language_list": [],
                    "week_schedule": [
                        [],
                        [],
                        [],
                        [],
                        [],
                        [],
                        []
                    ],
                    "product_platform_id": "0",
                    "mcc_mnc": [],
                    "age": [
                        [
                            18,
                            24
                        ],
                        [
                            25,
                            34
                        ],
                        [
                            35,
                            44
                        ],
                        [
                            45,
                            54
                        ],
                        [
                            55,
                            100
                        ]
                    ],
                    "contextual_tags": [],
                    "smart_interest_behavior": 0,
                    "ac": [],
                    "in_market_tags": [],
                    "last_frame": [],
                    "dpa_open_url_type": 0,
                    "cpa_bid": "",
                    "creative_material_mode": 2,
                    "app_type": 0,
                    "carriers": [],
                    "objective_type": 15,
                    "avatar_icon": {
                        "hash": "",
                        "url": "",
                        "uri": "",
                        "height": 100,
                        "width": 100,
                        "web_uri": ""
                    },
                    "dpa_retargeting_type": 0,
                    "app_retargeting_type": 0,
                    "ad_category_detail": 0,
                    "bid": "",
                    "classify": 1,
                    "province": [],
                    "brand_safety_partner": 0,
                    "flow_package_exclude": [],
                    "interest_keywords_lang_i18n": [],
                    "duration_time_range": 0,
                    "is_open_url": 0,
                    "zipcode_ids": [],
                    "smart_age": 0,
                    "saved_audience_id": 0,
                    "effective_frame": [],
                    "product_set_id": "0",
                    "launch_price": [],
                    "identity_type": 0,
                    "deep_external_action": 0,
                    "params_type": 0,
                    "is_rf_premium_inventory": false,
                    "schedule_type": 1,
                    "origin_ad_id": 0,
                    "dpa_local_audience": 0,
                    "deep_bid_type": 0,
                    "inventory_flow_type": 1,
                    "pixel_connected_domains": [],
                    "fake_ad_ids": [
                        "1811705000131601"
                    ],
                    "is_drop": 0,
                    "rf_notify_users": [],
                    "unified_game_id": "",
                    "search_keywords": [],
                    "device_type": 0,
                    "supply_catalog_id": "",
                    "retargeting_audience_rule": {
                        "inclusions": null,
                        "exclusions": null
                    },
                    "rf_estimate_key": "0",
                    "game_bc_id": "",
                    "plan_version_type": 0,
                    "vertical_suitability_id": 0,
                    "compliance_signature": "",
                    "op_sys_filter": 0,
                    "suitability_non_garm_category": [],
                    "content_type": 1,
                    "num": 1,
                    "coming_source_type": 0,
                    "sketch_publish_source": 0,
                    "collection_id": "",
                    "supply_bc_id": "",
                    "catalog_store_type": 0
                }
            },
            "creative_info": {
                "ad_ids": [
                    "0"
                ],
                "inventory_flow": [
                    3000
                ],
                "inventory_flow_type": 1,
                "objective_type": 15,
                "creative_material_mode": 2,
                "ad_channel": 1,
                "risk_info": {
                    "cookie_enabled": true,
                    "screen_width": 1728,
                    "screen_height": 1117,
                    "browser_language": "zh",
                    "browser_platform": "MacIntel",
                    "browser_name": "Mozilla",
                    "browser_version": "5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
                    "browser_online": true,
                    "timezone_name": "Asia/Shanghai"
                },
                "playable_url": "",
                "coming_source_type": 6,
                "creative_info": {
                    "video_list": [
                        {
                            "creative_name": "3 fetch",
                            "app_name": "Newcore®",
                            "source": "",
                            "title": "shilajit，Empowering men to reach their peak potential#holistichealth #naturalremedy #wellness #health #holistichealing #viral",
                            "call_to_action": "shop_now",
                            "avatar_icon": {
                                "url": "https://p19-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/2717caca161a7ca749f511e2d13dc484~c5_100x100.jpeg?lk3s=a5d48078&nonce=71772&refresh_token=79488400981b901b3b8eac815ac04ee2&x-expires=1727946000&x-signature=xG7MUzbNZN%2BSYZkUsqnqe1X4RuI%3D&shp=a5d48078&shcp=8aecc5ac",
                                "width": 0,
                                "web_uri": "",
                                "height": 0
                            },
                            "image_info": [
                                {
                                    "url": "https://p16-sign-va.tiktokcdn.com/tos-maliva-p-0068c799-us/oQOIRXL50IGe7sGALwZAewIfNlQkjx2IqU7REC~tplv-noop.image?x-expires=1727798203&x-signature=8iVh7CyjZg6%2Fm%2Bm1KcLXmuy3PYU%3D",
                                    "width": 2160,
                                    "web_uri": "",
                                    "height": 3840
                                }
                            ],
                            "video_info": {
                                "definition": "2160p",
                                "video_id": "v15044gf0000crp8ivfog65r7u3chqc0",
                                "vid": "v15044gf0000crp8ivfog65r7u3chqc0",
                                "format": "mp4",
                                "play_url": "https://v16-tt4b.tiktokcdn-us.com/7beeea01c2f2361661f442c791ebf6e4/66fc1bbc/video/tos/useast8/tos-useast8-ve-0068c002-tx2/oEfmioeV8BEibYYIQEI37EAO6PlAhmY4BERyiX/?a=1233&bti=Nzc2QDAzNmA%3D&ch=0&cr=0&dr=0&lr=unwatermarked&cd=0%7C0%7C0%7C0&cv=1&br=1374&bt=687&cs=0&ds=6&ft=GcD1VInz7ThF8t.rXq8Zmo&mime_type=video_mp4&qs=0&rc=N2g6Ojo8aDRoNzUzZ2VmOkBpM3RmeHU5cnk7dTMzaTczNEBjNDNiNTJgNTAxMmBjLzYyYSNgZTA0MmRjZm1gLS1kMTJzcw%3D%3D&vvpl=1&l=2024100109554462C86175E33B2A913415&btag=e00088000",
                                "cover_uri": "",
                                "cover_url": "https://p16-sign-va.tiktokcdn.com/tos-maliva-p-0068c799-us/oQOIRXL50IGe7sGALwZAewIfNlQkjx2IqU7REC~tplv-noop.image?x-expires=1727798204&x-signature=DoHbPPCYup%2BVeBUFOELiy78rWWs%3D",
                                "height": 3840,
                                "width": 2160,
                                "fps": 59,
                                "file_size": 198748030,
                                "duration": 57.934,
                                "file_md5": "bbedfd9e408a99dd17aed917b9b76c78",
                                "bitrate": 27444751,
                                "size": 198748030
                            },
                            "is_creative_authorized": false,
                            "item_source": 2,
                            "struct_version": 1,
                            "image_mode": 15,
                            "identity_id": "0b6b1c7f-90e0-56c2-8313-9e192526e159",
                            "identity_tts_shop_id": "",
                            "identity_authorized_shop_id": "0",
                            "identity_type": 5,
                            "is_open_url": 0,
                            "open_url": "",
                            "is_open_url_instant_page": 0,
                            "open_url_instant_page": "",
                            "auto_open": 0,
                            "fallback_type": 0,
                            "external_url": "",
                            "utms": [],
                            "open_url_utms": [],
                            "utm_auto_switch": 2,
                            "track_url": [],
                            "action_track_url": [],
                            "vast_moat": 0,
                            "vast_double_verify": 0,
                            "vast_ias": false,
                            "vast_url": "",
                            "brand_safety_postbid_partner": 0,
                            "external_url_domain": "",
                            "brand_safety_vast_url": "",
                            "tracking_pixel_id": "",
                            "tracking_app_id": "0",
                            "tracking_message_event_set_id": "",
                            "dpa_products": [],
                            "card_id": "",
                            "page_id": "",
                            "format_structure": 0,
                            "creative_type": 112,
                            "landing_page_strategy": 0,
                            "vertical_creative_strategy": 0,
                            "vertical_video_strategy": 1,
                            "vertical_image_strategy": 0,
                            "params_type": 0,
                            "dpa_open_url_type": 0,
                            "is_dynamic": 0,
                            "video_tpl_name": "",
                            "product_specific_type": 0,
                            "spu_list": [
                                "1729668374802174061"
                            ],
                            "showcase_spu_list": [],
                            "spu_custom_details": {},
                            "aweme_item_id": "7418143055884127518",
                            "identity_bc_id": "7417414952279097345",
                            "with_promotional_music": true,
                            "item_duet_disabled": 2,
                            "item_stitch_disabled": 2,
                            "carousel_a_i_image_mode": 1,
                            "by_creative_async_id": "626d96ba-c72f-4049-912b-c59107872a59",
                            "shop_ads_format_version": 1
                        },
                        {
                            "creative_name": "4",
                            "app_name": "Newcore®",
                            "source": "",
                            "title": "Energy levels been different lately #fyp #shilajit #shilajitgummies #health #energy #gymtok #gymrat #viral",
                            "call_to_action": "shop_now",
                            "avatar_icon": {
                                "url": "https://p19-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/2717caca161a7ca749f511e2d13dc484~c5_100x100.jpeg?lk3s=a5d48078&nonce=71772&refresh_token=79488400981b901b3b8eac815ac04ee2&x-expires=1727946000&x-signature=xG7MUzbNZN%2BSYZkUsqnqe1X4RuI%3D&shp=a5d48078&shcp=8aecc5ac",
                                "width": 0,
                                "web_uri": "",
                                "height": 0
                            },
                            "image_info": [
                                {
                                    "url": "https://p16-sign-va.tiktokcdn.com/tos-maliva-p-0068c799-us/osZELCyElVIIAlBRSjiinxiJWKCGKJIFAPzBv~tplv-noop.image?x-expires=1727798197&x-signature=i%2FMfPbObFjXd7fY5yv8co32X9%2B4%3D",
                                    "width": 2160,
                                    "web_uri": "",
                                    "height": 3840
                                }
                            ],
                            "video_info": {
                                "definition": "2160p",
                                "video_id": "v15044gf0000crp8j57og65h41a8h350",
                                "vid": "v15044gf0000crp8j57og65h41a8h350",
                                "format": "mp4",
                                "play_url": "https://v16-tt4b.tiktokcdn-us.com/2e82c91bb0c3fe7464ba9f2c4ecfd0ab/66fc1bb6/video/tos/useast8/tos-useast8-ve-0068c003-tx2/ooBTEyZBixIiSlAFG0jQKIRInBJPDviKVAEmD/?a=1233&bti=Nzc2QDAzNmA%3D&ch=0&cr=0&dr=0&lr=unwatermarked&cd=0%7C0%7C0%7C0&cv=1&br=2150&bt=1075&cs=0&ds=6&ft=GcD1VInz7ThF8t.rXq8Zmo&mime_type=video_mp4&qs=0&rc=NTQ6Omc6ZThoZzppZTVmOEBpMzY7NGs5cjg7dTMzaTczNEBjYmIzXmI2XjIxLV4xYWE0YSMyZV4xMmQ0Z21gLS1kMTJzcw%3D%3D&vvpl=1&l=2024100109554462C86175E33B2A913415&btag=e00088000",
                                "cover_uri": "",
                                "cover_url": "https://p16-sign-va.tiktokcdn.com/tos-maliva-p-0068c799-us/osZELCyElVIIAlBRSjiinxiJWKCGKJIFAPzBv~tplv-noop.image?x-expires=1727798198&x-signature=FEudXhdQlK%2FnnYul51Wu4kCAt9E%3D",
                                "height": 3840,
                                "width": 2160,
                                "fps": 30,
                                "file_size": 253806174,
                                "duration": 51.92,
                                "file_md5": "685d0664b86db9a832794b56390873a4",
                                "bitrate": 39107268,
                                "size": 253806174
                            },
                            "is_creative_authorized": false,
                            "item_source": 2,
                            "struct_version": 1,
                            "image_mode": 15,
                            "identity_id": "0b6b1c7f-90e0-56c2-8313-9e192526e159",
                            "identity_tts_shop_id": "",
                            "identity_authorized_shop_id": "0",
                            "identity_type": 5,
                            "is_open_url": 0,
                            "open_url": "",
                            "is_open_url_instant_page": 0,
                            "open_url_instant_page": "",
                            "auto_open": 0,
                            "fallback_type": 0,
                            "external_url": "",
                            "utms": [],
                            "open_url_utms": [],
                            "utm_auto_switch": 2,
                            "track_url": [],
                            "action_track_url": [],
                            "vast_moat": 0,
                            "vast_double_verify": 0,
                            "vast_ias": false,
                            "vast_url": "",
                            "brand_safety_postbid_partner": 0,
                            "external_url_domain": "",
                            "brand_safety_vast_url": "",
                            "tracking_pixel_id": "",
                            "tracking_app_id": "0",
                            "tracking_message_event_set_id": "",
                            "dpa_products": [],
                            "card_id": "",
                            "page_id": "",
                            "format_structure": 0,
                            "creative_type": 112,
                            "landing_page_strategy": 0,
                            "vertical_creative_strategy": 0,
                            "vertical_video_strategy": 1,
                            "vertical_image_strategy": 0,
                            "params_type": 0,
                            "dpa_open_url_type": 0,
                            "is_dynamic": 0,
                            "video_tpl_name": "",
                            "product_specific_type": 0,
                            "spu_list": [
                                "1729668374802174061"
                            ],
                            "showcase_spu_list": [],
                            "spu_custom_details": {},
                            "aweme_item_id": "7418143545632115998",
                            "identity_bc_id": "7417414952279097345",
                            "with_promotional_music": true,
                            "item_duet_disabled": 2,
                            "item_stitch_disabled": 2,
                            "carousel_a_i_image_mode": 1,
                            "by_creative_async_id": "fbde11e9-9bcc-4831-bc8e-3843d20bc712",
                            "shop_ads_format_version": 1
                        },
                        {
                            "creative_name": "5",
                            "app_name": "Newcore®",
                            "source": "",
                            "title": "shilajit，Empowering men to reach their peak potential#holistichealth #naturalremedy #wellness #health #holistichealing #viral",
                            "call_to_action": "shop_now",
                            "avatar_icon": {
                                "url": "https://p19-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/2717caca161a7ca749f511e2d13dc484~c5_100x100.jpeg?lk3s=a5d48078&nonce=71772&refresh_token=79488400981b901b3b8eac815ac04ee2&x-expires=1727946000&x-signature=xG7MUzbNZN%2BSYZkUsqnqe1X4RuI%3D&shp=a5d48078&shcp=8aecc5ac",
                                "width": 0,
                                "web_uri": "",
                                "height": 0
                            },
                            "image_info": [
                                {
                                    "url": "https://p16-sign-va.tiktokcdn.com/tos-maliva-p-0068c799-us/oAy9A8DE7QmpFf4mgVfBR3qqhhC9ioEWAEEqFI~tplv-noop.image?x-expires=1727798189&x-signature=MnWFQj3ZeVhFVfa1lihLiRyIkJw%3D",
                                    "width": 2160,
                                    "web_uri": "",
                                    "height": 3840
                                }
                            ],
                            "video_info": {
                                "definition": "2160p",
                                "video_id": "v15044gf0000crp8janog65gtvldo1ag",
                                "vid": "v15044gf0000crp8janog65gtvldo1ag",
                                "format": "mp4",
                                "play_url": "https://v16-tt4b.tiktokcdn-us.com/42d376f905670ab3d6a0edfc53f877f7/66fc1bae/video/tos/useast8/tos-useast8-ve-0068c001-tx2/osmEVfoycAxRDqEEQrhEAqBViE8FI8pemBm3pT/?a=1233&bti=Nzc2QDAzNmA%3D&ch=0&cr=0&dr=0&lr=unwatermarked&cd=0%7C0%7C0%7C0&cv=1&br=1752&bt=876&cs=0&ds=6&ft=GcD1VInz7ThF8t.rXq8Zmo&mime_type=video_mp4&qs=0&rc=aWg7aGQ4O2U6NWZoZmhpZEBpajRneWo5cmQ7dTMzaTczNEA1X2AuNjQ0NTExNTAxMC0zYSNebGlxMmRrZ21gLS1kMTJzcw%3D%3D&vvpl=1&l=2024100109554462C86175E33B2A913415&btag=e00088000",
                                "cover_uri": "",
                                "cover_url": "https://p16-sign-va.tiktokcdn.com/tos-maliva-p-0068c799-us/oAy9A8DE7QmpFf4mgVfBR3qqhhC9ioEWAEEqFI~tplv-noop.image?x-expires=1727798190&x-signature=i9ntAND7uFd9FHo4TbVttOOwMos%3D",
                                "height": 3840,
                                "width": 2160,
                                "fps": 60,
                                "file_size": 194872435,
                                "duration": 43.399,
                                "file_md5": "97f7324b4f979f2c587681a5660abc7e",
                                "bitrate": 35922013,
                                "size": 194872435
                            },
                            "is_creative_authorized": false,
                            "item_source": 2,
                            "struct_version": 1,
                            "image_mode": 15,
                            "identity_id": "0b6b1c7f-90e0-56c2-8313-9e192526e159",
                            "identity_tts_shop_id": "",
                            "identity_authorized_shop_id": "0",
                            "identity_type": 5,
                            "is_open_url": 0,
                            "open_url": "",
                            "is_open_url_instant_page": 0,
                            "open_url_instant_page": "",
                            "auto_open": 0,
                            "fallback_type": 0,
                            "external_url": "",
                            "utms": [],
                            "open_url_utms": [],
                            "utm_auto_switch": 2,
                            "track_url": [],
                            "action_track_url": [],
                            "vast_moat": 0,
                            "vast_double_verify": 0,
                            "vast_ias": false,
                            "vast_url": "",
                            "brand_safety_postbid_partner": 0,
                            "external_url_domain": "",
                            "brand_safety_vast_url": "",
                            "tracking_pixel_id": "",
                            "tracking_app_id": "0",
                            "tracking_message_event_set_id": "",
                            "dpa_products": [],
                            "card_id": "",
                            "page_id": "",
                            "format_structure": 0,
                            "creative_type": 112,
                            "landing_page_strategy": 0,
                            "vertical_creative_strategy": 0,
                            "vertical_video_strategy": 1,
                            "vertical_image_strategy": 0,
                            "params_type": 0,
                            "dpa_open_url_type": 0,
                            "is_dynamic": 0,
                            "video_tpl_name": "",
                            "product_specific_type": 0,
                            "spu_list": [
                                "1729668374802174061"
                            ],
                            "showcase_spu_list": [],
                            "spu_custom_details": {},
                            "aweme_item_id": "7418143564376378655",
                            "identity_bc_id": "7417414952279097345",
                            "with_promotional_music": true,
                            "item_duet_disabled": 2,
                            "item_stitch_disabled": 2,
                            "carousel_a_i_image_mode": 1,
                            "by_creative_async_id": "a5dfa0cf-41d8-48cf-b46d-96d7f1fcbab8",
                            "shop_ads_format_version": 1
                        },
                        {
                            "creative_name": "1",
                            "app_name": "Newcore®",
                            "source": "",
                            "title": "shilajit，Empowering men to reach their peak potential#holistichealth #naturalremedy #wellness #health #holistichealing #viralvideo #fypシ゚ #foryouuu #love",
                            "call_to_action": "shop_now",
                            "avatar_icon": {
                                "url": "https://p19-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/2717caca161a7ca749f511e2d13dc484~c5_100x100.jpeg?lk3s=a5d48078&nonce=71772&refresh_token=79488400981b901b3b8eac815ac04ee2&x-expires=1727946000&x-signature=xG7MUzbNZN%2BSYZkUsqnqe1X4RuI%3D&shp=a5d48078&shcp=8aecc5ac",
                                "width": 0,
                                "web_uri": "",
                                "height": 0
                            },
                            "image_info": [
                                {
                                    "url": "https://p16-sign-va.tiktokcdn.com/tos-maliva-p-0068c799-us/owEoYMIAVnAFGE9vXeRah8f9R4D6EBGQoDHm3n~tplv-noop.image?x-expires=1727798181&x-signature=Tjj4WMe163ViyI87FbRsfTs0jx8%3D",
                                    "width": 2160,
                                    "web_uri": "",
                                    "height": 3840
                                }
                            ],
                            "video_info": {
                                "definition": "2160p",
                                "video_id": "v15044gf0000crpts37og65gtvmh8d1g",
                                "vid": "v15044gf0000crpts37og65gtvmh8d1g",
                                "format": "mp4",
                                "play_url": "https://v16-tt4b.tiktokcdn-us.com/a1b5be42c8b6b2e797905e1c60da332c/66fc1ba6/video/tos/useast8/tos-useast8-ve-0068c003-tx2/oEpEDf9zUABRDpEEQ0hEAMBV3E8FIJuemN43Mj/?a=1233&bti=Nzc2QDAzNmA%3D&ch=0&cr=0&dr=0&lr=unwatermarked&cd=0%7C0%7C0%7C0&cv=1&br=1962&bt=981&cs=0&ds=6&ft=GcD1VInz7ThF8t.rXq8Zmo&mime_type=video_mp4&qs=0&rc=OjU5NDhmNjdmNDc2ZmY0O0BpamdreWo5cjZ3dTMzaTczNEBfLjAtM2FeXjIxNV42Yi4yYSMuNWpxMmQ0cG1gLS1kMTJzcw%3D%3D&vvpl=1&l=2024100109554462C86175E33B2A913415&btag=e00088000",
                                "cover_uri": "",
                                "cover_url": "https://p16-sign-va.tiktokcdn.com/tos-maliva-p-0068c799-us/owEoYMIAVnAFGE9vXeRah8f9R4D6EBGQoDHm3n~tplv-noop.image?x-expires=1727798182&x-signature=or6oEbgXoEdb%2B04r1i%2F9CzgaKuQ%3D",
                                "height": 3840,
                                "width": 2160,
                                "fps": 40,
                                "file_size": 120711468,
                                "duration": 35.016,
                                "file_md5": "53e709739fb386d135f5ac2396eb433f",
                                "bitrate": 27578585,
                                "size": 120711468
                            },
                            "is_creative_authorized": false,
                            "item_source": 2,
                            "struct_version": 1,
                            "image_mode": 15,
                            "identity_id": "0b6b1c7f-90e0-56c2-8313-9e192526e159",
                            "identity_tts_shop_id": "",
                            "identity_authorized_shop_id": "0",
                            "identity_type": 5,
                            "is_open_url": 0,
                            "open_url": "",
                            "is_open_url_instant_page": 0,
                            "open_url_instant_page": "",
                            "auto_open": 0,
                            "fallback_type": 0,
                            "external_url": "",
                            "utms": [],
                            "open_url_utms": [],
                            "utm_auto_switch": 2,
                            "track_url": [],
                            "action_track_url": [],
                            "vast_moat": 0,
                            "vast_double_verify": 0,
                            "vast_ias": false,
                            "vast_url": "",
                            "brand_safety_postbid_partner": 0,
                            "external_url_domain": "",
                            "brand_safety_vast_url": "",
                            "tracking_pixel_id": "",
                            "tracking_app_id": "0",
                            "tracking_message_event_set_id": "",
                            "dpa_products": [],
                            "card_id": "",
                            "page_id": "",
                            "format_structure": 0,
                            "creative_type": 112,
                            "landing_page_strategy": 0,
                            "vertical_creative_strategy": 0,
                            "vertical_video_strategy": 1,
                            "vertical_image_strategy": 0,
                            "params_type": 0,
                            "dpa_open_url_type": 0,
                            "is_dynamic": 0,
                            "video_tpl_name": "",
                            "product_specific_type": 0,
                            "spu_list": [
                                "1729668374802174061"
                            ],
                            "showcase_spu_list": [],
                            "spu_custom_details": {},
                            "aweme_item_id": "7418517475983133982",
                            "identity_bc_id": "7417414952279097345",
                            "with_promotional_music": true,
                            "item_duet_disabled": 2,
                            "item_stitch_disabled": 2,
                            "carousel_a_i_image_mode": 1,
                            "by_creative_async_id": "3aec9813-cbee-49cc-b7ae-ad32afbbd9c6",
                            "shop_ads_format_version": 1
                        },
                        {
                            "creative_name": "2",
                            "app_name": "Newcore®",
                            "source": "",
                            "title": "shilajit，Empowering men to reach their peak potential#holistichealth #naturalremedy #wellness #health #holistichealing #viral",
                            "call_to_action": "shop_now",
                            "avatar_icon": {
                                "url": "https://p19-pu-sign-useast8.tiktokcdn-us.com/tos-useast5-avt-0068-tx/2717caca161a7ca749f511e2d13dc484~c5_100x100.jpeg?lk3s=a5d48078&nonce=71772&refresh_token=79488400981b901b3b8eac815ac04ee2&x-expires=1727946000&x-signature=xG7MUzbNZN%2BSYZkUsqnqe1X4RuI%3D&shp=a5d48078&shcp=8aecc5ac",
                                "width": 0,
                                "web_uri": "",
                                "height": 0
                            },
                            "image_info": [
                                {
                                    "url": "https://p16-sign-va.tiktokcdn.com/tos-maliva-p-0068c799-us/ok7FGM8cNfIfGNflCUWQANM5I5AjrP2gQ18iqR~tplv-noop.image?x-expires=1727798189&x-signature=TrCZekMuLs6Za0J8AliV4%2BYPw2g%3D",
                                    "width": 2160,
                                    "web_uri": "",
                                    "height": 3840
                                }
                            ],
                            "video_info": {
                                "definition": "2160p",
                                "video_id": "v15044gf0000crp8jf7og65ijbrvh3bg",
                                "vid": "v15044gf0000crp8jf7og65ijbrvh3bg",
                                "format": "mp4",
                                "play_url": "https://v16-tt4b.tiktokcdn-us.com/a2934c380e1aa4e0dcee94bdf53f65af/66fc1bae/video/tos/useast8/tos-useast8-ve-0068c004-tx2/ooiRNIEKNQG4AfA5Ip3ICQeyXqLoj5jIaEKaen/?a=1233&bti=Nzc2QDAzNmA%3D&ch=0&cr=0&dr=0&lr=unwatermarked&cd=0%7C0%7C0%7C0&cv=1&br=1744&bt=872&cs=0&ds=6&ft=GcD1VInz7ThF8t.rXq8Zmo&mime_type=video_mp4&qs=0&rc=ZmY4NTYzNGg6OWU7ZDRoNkBpajZ5ZWw5cmk7dTMzaTczNEBiNDBiMmEwNmMxYS4wNjEzYSNfZW9nMmQ0Z21gLS1kMTJzcw%3D%3D&vvpl=1&l=2024100109554462C86175E33B2A913415&btag=e00088000",
                                "cover_uri": "",
                                "cover_url": "https://p16-sign-va.tiktokcdn.com/tos-maliva-p-0068c799-us/ok7FGM8cNfIfGNflCUWQANM5I5AjrP2gQ18iqR~tplv-noop.image?x-expires=1727798190&x-signature=XyoZDzhwi6DhyOVx5relsQKPtuQ%3D",
                                "height": 3840,
                                "width": 2160,
                                "fps": 60,
                                "file_size": 175539902,
                                "duration": 43.399,
                                "file_md5": "d70a79a7c44541b00ba270645e4babb7",
                                "bitrate": 32358331,
                                "size": 175539902
                            },
                            "is_creative_authorized": false,
                            "item_source": 2,
                            "struct_version": 1,
                            "image_mode": 15,
                            "identity_id": "0b6b1c7f-90e0-56c2-8313-9e192526e159",
                            "identity_tts_shop_id": "",
                            "identity_authorized_shop_id": "0",
                            "identity_type": 5,
                            "is_open_url": 0,
                            "open_url": "",
                            "is_open_url_instant_page": 0,
                            "open_url_instant_page": "",
                            "auto_open": 0,
                            "fallback_type": 0,
                            "external_url": "",
                            "utms": [],
                            "open_url_utms": [],
                            "utm_auto_switch": 2,
                            "track_url": [],
                            "action_track_url": [],
                            "vast_moat": 0,
                            "vast_double_verify": 0,
                            "vast_ias": false,
                            "vast_url": "",
                            "brand_safety_postbid_partner": 0,
                            "external_url_domain": "",
                            "brand_safety_vast_url": "",
                            "tracking_pixel_id": "",
                            "tracking_app_id": "0",
                            "tracking_message_event_set_id": "",
                            "dpa_products": [],
                            "card_id": "",
                            "page_id": "",
                            "format_structure": 0,
                            "creative_type": 112,
                            "landing_page_strategy": 0,
                            "vertical_creative_strategy": 0,
                            "vertical_video_strategy": 1,
                            "vertical_image_strategy": 0,
                            "params_type": 0,
                            "dpa_open_url_type": 0,
                            "is_dynamic": 0,
                            "video_tpl_name": "",
                            "product_specific_type": 0,
                            "spu_list": [
                                "1729668374802174061", // TODO: 商品id  
                            ],
                            "showcase_spu_list": [],
                            "spu_custom_details": {},
                            "aweme_item_id": "7418143563155868959",
                            "identity_bc_id": "7417414952279097345",
                            "with_promotional_music": true,
                            "item_duet_disabled": 2,
                            "item_stitch_disabled": 2,
                            "carousel_a_i_image_mode": 1,
                            "by_creative_async_id": "8a49f5f6-36f6-4ba4-a7ee-4fb7551ff797",
                            "shop_ads_format_version": 1
                        }
                    ]
                }
            }
        }
    ],
    "ad_channel": 1,
    "risk_info": {
        "cookie_enabled": true,
        "screen_width": 1728,
        "screen_height": 1117,
        "browser_language": "zh",
        "browser_platform": "MacIntel",
        "browser_name": "Mozilla",
        "browser_version": "5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
        "browser_online": true,
        "timezone_name": "Asia/Shanghai"
    }
};
fetch(
  "https://ads.tiktok.com/api/v3/i18n/perf/async_creation/create/?aadvid=7417667470661697537&msToken=-0G2nGU3WMsZDThv3VW5E7iEA-wwlbPQl4y7vs6jmLPlpWE00mp91nRICbMjVajhdRbq0_yyoggarvnyjw1c3kSW-8Pqrl9Xsk1S5cDMvKyPoFSRBAEDnJ37AwpqDz0aiSQbNw==&X-Bogus=DFSzswVL6OVaxyent6SpIU9WcBnQ&_signature=_02B4Z6wo00001KZCfRgAAIDApkJ9Gtg0p3ymQnmAAE9wff",
  {
    headers: {
      accept: "application/json, text/plain, */*",
      "content-type": "application/json",
      "sec-fetch-mode": "cors",
      "sec-fetch-site": "same-origin",
      "x-csrftoken": "2s0hHtqOmT4VtDqKXn8B3MU29GLiogmd",
    },
    body: JSON.stringify({bodyParams}),  
    method: "POST",
  }
);
